### ISSUE TITLE
Should Data.Monoid.Linear re-export Data.Semigroup?

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#103]
I haven't examined this closely, but we might want linear versions of what's re-exported in Data.Semigroup.

**Comment by utdemir** [comment]
This is relevant to the PR: https://github.com/tweag/linear-base/pull/133

I think it should export linear versions of whatever inside `Data.Semigroup` and `Data.Monoid`. Especially linear accessors for things like `All` and `Dual` would be useful.

**Comment by utdemir** [comment]
It seems like it does re-export it:

https://github.com/tweag/linear-base/blob/becc65418ff359c022e2e49217eb314d633c66b2/src/Data/Monoid/Linear.hs#L14-L23

Should we close this issue @Divesh-Otwani ?

**Comment by Divesh-Otwani** [comment]
Sure, closing. The more general point is that we should have a `Data.Semigroup.Linear` module and so on.
