### ISSUE TITLE
Which "Unrestricted Maybe" should be standard?

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#116]
In the lookup of a hashmap and similar cases, we have a common pattern of wanting something like one of the following options. Which one should we choose?

- `Maybe (Unrestricted a)`
- `Unrestricted (Maybe a)`
- `data MaybeU a where MaybeU :: a -> MaybeU a`

**Comment by utdemir** [comment]
I think we should reuse the existing `Maybe` and `Unrestricted` types; just because it is one less thing to learn. However, between the initial two options, I do not have a strong preference.

**Comment by facundominguez** [comment]
`Unrestricted (Maybe a)` is better than `Maybe (Unrestricted a)`. Is there any reason to force the caller to consume the Maybe?

**Comment by aspiwack** [comment]
They are isomorphic types. But I think that we could summarize your point, @facundominguez , by: let's have `Unrestricted` as early as possible, because it's syntactically more convenient.

I'm inclined to agree, actually.

**Comment by Divesh-Otwani** [comment]
I agree @aspiwack :smile:  When `Unrestricted` is renamed to something short, putting it on the outside works nicely: `Lax (Maybe a)` or something seems good enough for me. Can I close this issue @aspiwack @facundominguez @utdemir?

**Comment by aspiwack** [comment]
Yes. Let's have `Unrestricted (Maybe a)`.

**Comment by Divesh-Otwani** [comment]
Closing with the decision of using `Unrestricted (Maybe a)`.
