### ISSUE TITLE
Prelude.Monad instance for linear IO

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#117]
In order to use do-notation with -XRebindableSyntax with linear IO (which came up when writing linear-streams), the linear IO monad needs a regular Prelude monad instance.

**Comment by aspiwack** [comment]
I don't understand.

- Why would you need a `Prelude.Monad` instance if you have `-XRebindableSyntax` (there are a number of example of linear IO with do notation in linear base anyway)?
- Linear IO (critically) can't have a `Prelude.Monad` instance.

**Comment by Divesh-Otwani** [comment]
Yes, this issue makes no sense. Something else is going on with the error I'm seeing in developing linear streams.
