### ISSUE TITLE
problems using linear-base in a new project

### ISSUE THREAD

**Issue by silky** [tweag/linear-base#120]
I've followed the steps from the readme in a new project, and I get the following error:

```
02:12 PM noon ∈ linear-types stack build
Stack has not been tested with GHC versions above 8.10, and using 8.11, this may fail
Stack has not been tested with Cabal versions above 3.2, but version 3.3.0.0 was found, this may fail
WARNING: Ignoring vector's bounds on base (>=4.5 && <4.15); using base-4.15.0.0.
Reason: allow-newer enabled.
WARNING: Ignoring primitive's bounds on base (>=4.5 && <4.15); using base-4.15.0.0.
Reason: allow-newer enabled.
primitive      > configure
primitive      > Configuring primitive-0.7.0.0...
primitive      > build
primitive      > Preprocessing library for primitive-0.7.0.0..
primitive      > Building library for primitive-0.7.0.0..
primitive      > [ 1 of 13] Compiling Control.Monad.Primitive
primitive      > 
primitive      > /run/user/1000/stack-fc9f49f9c873bb1e/primitive-0.7.0.0/Control/Monad/Primitive.hs:27:21: error:
primitive      >     Module ‘GHC.Base’ does not export ‘unsafeCoerce#’
primitive      >    |
primitive      > 27 | import GHC.Base   ( unsafeCoerce#, realWorld# )
primitive      >    |                     ^^^^^^^^^^^^^
            
--  While building package primitive-0.7.0.0 using:
      /home/noon/.stack/setup-exe-cache/x86_64-linux-nix/Cabal-simple_mPHDZzAJ_3.3.0.0_ghc-8.11.20200630 --builddir=.stack-work/dist/x86_64-linux-nix/Cabal-3.3.0.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Progress 1/4
```

**To Reproduce**

1. Start a new project with `stack new linear-types --bare simple-hpack`
2. Follow the README - https://github.com/tweag/linear-base#getting-started
3. Build with `stack build`

**Expected behavior**

The build to work!

**Environment**
 - OS name + version: Linux 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Version of the code: Tried with the revision in the readme, as well as `705522f0bad3f1083bb3447b9f476f6f84d21410`

**Comment by silky** [comment]
if it's relevant, i _was_ able to build this project itself, but i get lots of `Failed to decode module interface` errors when building, or running the tests; errors such as:

```
...
Warning: Failed to decode module interface:
         /home/noon/dev/linear-base/.stack-work/dist/x86_64-linux-nix/Cabal-3.3.0.0/build/Control/Monad/Linear/Internal.hi
         Decoding failure: not enough bytes
....
```

**Comment by facundominguez** [comment]
> Warning: Failed to decode module interface:

This shows up in CI, but it doesn't seem to hamper the ability to run the tests.

I updated the readme in the linked PR. Thanks for opening the issue!

**Comment by aspiwack** [comment]
Ah yes. Building Hackage stuff with a GHC close to master is a bit of a moving target. We will see some more of this, probably. Until the beta is out.

@silky Thanks a lot for trying this out. Hope this is going to be interesting. If you find any bug regarding linear types don't hesitate report them on GHC's Gitlab. We have [a label](https://gitlab.haskell.org/ghc/ghc/-/issues?scope=all&utf8=%E2%9C%93&state=opened&label_name[]=LinearTypes) dedicated to linear types. For now, it's way too empty, to be honest.

**Comment by silky** [comment]
thanks for the fix @facundominguez ; it works now :)
