### ISSUE TITLE
stack ghci panics

### ISSUE THREAD

**Issue by aspiwack** [tweag/linear-base#123]
As of right now, calling `stack ghci` will panic when loading `Data.Unsafe.MutableArray`. It appears to be a regression related to `runRW#`.

The following code works in current ghci, and panics in the ghci version which is pinned in linear-base nix-shell:
```haskell
> :set -XMagicHash
> import GHC.Exts
> runRW# $ \s -> 0
```
As long as this bug persists, we can't use `ghcid` with linear-base, which is rather no bueno. (though I'm not sure it's the only hurdle for this particular race, currently)

This is probably [upstream's 18397](https://gitlab.haskell.org/ghc/ghc/-/issues/18397). It's being fixed. So this is a reminder to track said issue, and update our head as soon as the bug is fixed.

**Comment by utdemir** [comment]
Just to note, running `ghci` with `-fno-code` (I tried `cabal repl --repl-options '-fno-code'`) seems to not have this issue; so it might be a temporary workaround for `ghcid`.

**Comment by aspiwack** [comment]
Indeed. Well spotted.

**Comment by utdemir** [comment]
I confirmed that this issue is fixed at the current GHC HEAD. I created https://github.com/NixOS/nixpkgs/pull/96125 to update the compiler on nixpkgs, and I'll update our nixpkgs pin once that is merged.
