### ISSUE TITLE
The Big Bikeshedding Bonanza

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#127]
With the release of GHC 9.0, which will feature linear types, approaching; we are also preparing a release of linear-base.

And in order for this to happen, it is time to pay attention to some things which we had so far neglected. That is, stuff scoring high in the [Wadler's law](https://wiki.haskell.org/Wadler's_Law) scale. By virtue of them taking time, we have consistently put off thinking about naming too much, and ploughed forward with temporary names for many things, so that we could make progress on implementation.

But now is the time. We have the [bikeshedding label](https://github.com/tweag/linear-base/labels/Bikeshedding) to group these issues. So if you are into this sort of things, join us there and contribute your opinion.

**Comment by utdemir** [comment]
Here are some, about the module structure:

* When I import a `*.Linear` module, I expect to only get linear functions. and the data types those functions work on. It is surprising  to me that I can import `Prelude.Linear` and it contains non-linear functions.
* In some cases using `*.Linear` modules require some data types from `base` to be imported (eg. `Data.Maybe.Linear` does not export `Maybe (..)`, or `Data.Ord.Linear` does not export `Ordering`), which is a bit annoying.
* `Data.Functor.Linear` vs. `Control.Monad.Linear` is a bit confusing when I need to import a `Functor`. I'd expect both `{Data,Control}.Functor.Linear` to exist. `Monad` can either be inside of `Control.Functor.Linear`, or we can have a separate `Control.Monad.Linear`.
* Some modules does not have `Linear` suffix: `System.IO.Resource`, `Foreign.Marshall.Pure`.

**Comment by aspiwack** [comment]
@utdemir please make separate issues instead.

**Comment by Divesh-Otwani** [comment]
> Here are some, about the module structure:
> 
>     * When I import a `*.Linear` module, I expect to only get linear functions. and the data types those functions work on. It is surprising  to me that I can import `Prelude.Linear` and it contains non-linear functions.
> 
>     * In some cases using `*.Linear` modules require some data types from `base` to be imported (eg. `Data.Maybe.Linear` does not export `Maybe (..)`, or `Data.Ord.Linear` does not export `Ordering`), which is a bit annoying.
> 
>     * `Data.Functor.Linear` vs. `Control.Monad.Linear` is a bit confusing when I need to import a `Functor`. I'd expect both `{Data,Control}.Functor.Linear` to exist. `Monad` can either be inside of `Control.Functor.Linear`, or we can have a separate `Control.Monad.Linear`.
> 
>     * Some modules does not have `Linear` suffix: `System.IO.Resource`, `Foreign.Marshall.Pure`.

I *super* agree with everything above. In general, the "organizational changes" in the second bullet point of the roadmap includes this. A key principle that I hope to achieve in that pass is "each module should implement a single, self-contained concept that matches the module name". (The only other key principle is "we are aiming for heavily decoupled modules with a clean dependency hierarchy, enforced by explicit export lists".)

**Comment by aspiwack** [comment]
> A key principle that I hope to achieve in that pass is "each module should implement a single, self-contained concept that matches the module name".

As stated, this sounds like a bad idea. My goal is, on the contrary, to minimise the number of modules that you need to import. Importing things is a chore enough, no need to make it arbitrarily more tedious.

**Comment by Divesh-Otwani** [comment]
What I was thinking of was something like a well named (probably can't think of a good one right now) module like `Control.Prelude.Linear` which exports `Control.Functor`, `Control.Applicative`, `Control.Monad`, `Control.Monad.Builder` and so on. I'm not sure (and I don't have a lot of experience) but it seems better to me to have a lot of crisp, isolated modules and use "top level modules" to re-export things. I think it makes it easier to maintain things, naturally leads to decoupling and is generally more stable -- we can move stuff around across versions of linear base but keep the modules that re-export things the same.

**Comment by aspiwack** [comment]
Sure that'd work fine. I'm not sure it's super useful for something as short as the `Functor` modules (though the name need to be discussed, indeed. But again: separate issues).

**Comment by aspiwack** [comment]
This issue has no scope, its only role is to be a pinned issue to draw attention of any visitor who might be interested.

We'll close it when the first release is done.

**Comment by utdemir** [comment]
> We'll close it when the first release is done.

It is. I am closing this, but I if anyone else ends up here, please do open separate issues.
