### ISSUE TITLE
The name of Unrestricted

### ISSUE THREAD

**Issue by aspiwack** [tweag/linear-base#131]
This is something which has bothered everyone for months. It resurfaced recently in our internal discussion channels. We still don't have a clear solution.

The problem: `Unrestricted`, while a perfectly descriptive name, is very long. And considering how often this type is referred to in type signatures (and its constructor in function definition), we really want a shorter name. It's for everybody's sanity.

This naming issue can also be accompanied  by a reflection of how to name of the accompanying, and commonly useful

```haskell
data X s a where
  X :: s #-> a -> X s a
```
(the fields may be in the reverse order, I don't care much either way)

Here is a list of all the proposals that have been mooted that I can remember

- `Many`: but since it's already used for the name of the multiplicity, it invites many conflicts which are likely to be unpleasant.
- `Bang` after the fact that `Unrestricted a` is write `!a` in traditional linear logic literature. But it's fairly meaningless, if you don't know that notation.
- `Poly`: after _polynomial_ (linear: I must consume once, quadratic: I must consume twice, … polynomial: either of these). It does makes sense from a point of view of the mathematical analogy. And `Poly` means something like “several” in Greek, so it makes sense.
- `U`: first letter of `Unrestricted`. Easy to use, but a one-letter name may be consider a bit too rare and precious for this use.
- `This`: short, but ultimately hard to convey an intuition. It sounds a bit like it ought to mean the identity, which I don't think is a very good intuition. It could work if we have a story for how this makes sense. It does have the advantage that it comes with a reasonable name for `X`: ``s `AndThis` a``.
- `Lax`: mostly a synonymous of `Unrestricted`. But nobody's really convinced by it
- `Freely`, `Surely`: adverbs in the tradition of using such adverbs to pronounce modality (sometime `!a` is pronounced “certainly `a`”, see also “there merely exists” in homotopy type theory).
  - It could be a corresponding adjective, though `Free` is already taken, and `Sure` sounds weird. (like is “p is a mere proposition”)
  - Or an adverb of the same kind as `Maybe`
- `Box`: very generic
- `With`: this one has a bit of a twist, we would have 
   ```haskell
   type With :: Multiplicity -> Type -> Type
   data With p a where
     With :: a #p-> With p a
   ```
   So that `With 'Many a` is `Unrestricted a`. But since this last case is so common we would make a shorthand, such as `With'`.
- `More`: A bit like `Many`. Though it may sound a bit excessive, I guess.

I am, personally, fully convinced by none of these. But they are good starting points. Naming is hard. But, sometimes, after stumbling in the dark for a while, we suddenly fine the name which should have been obvious all along. Help me find it.

**Comment by gdeest** [comment]
Another adverbial suggestion: `AtWill`.

**Comment by utdemir** [comment]
I actually like `Lax`. It conveys the meaning well, and quite short. Alternative synonym: `Loose`.

I also thought of the words `Off` (like it's _escaping_ from the linear arrow), `Out` (as in "out of bounds"), and `Libre` ("free as in 'freedom', not 'free beer'"). But my favourite is still `Lax`.

**Comment by mboes** [comment]
Another few entries:

* The problem with `U` is that it's perhaps too greedy to steal such prime estate in the namespace as a single letter. But 2-letter or 3-letter names should be fine. For example, have `Unr` or `Ur`.
* Wikipedia says "!" is read "of course". So we could have `Ofc` for short. Cons: not particularly readable. Pros: short, and at least this way we don't have to invent anything new. We'd be following precedent.
* The `With` idea could work better if it was `Have`: `a #1 -> Have' 'Many b` and `a #1 -> Have b`.

**Comment by aspiwack** [comment]
Ah, yes, I had left `Have` out. Sorry to whoever proposed it earlier. I forgot.

A slight issue with `Have` is that the literature (think American-East-Coast-style multiple judgement sequent calculi) sometimes uses `have` for the linear judgement, if I remember correctly (and `true` for the non-linear judgement), with the intuition that unrestricted things, from a logical point of view represents (absolute) truth, while linear things are things that you have, but can expend.

So, for some, `Have` could have the opposite intuition.

Still, it's a good entrant.

**Comment by mboes** [comment]
Fair point. Another variation: `Get` or `Got`. Even shorter.

```haskell
a #1 -> Get' 'One b
a #1 -> Get b
```

**Comment by mboes** [comment]
I was reading Perl code this morning (don't ask...). It reminded me that they use `my` as a very short keyword to introduce new variables in scope with different scoping than the default (which is to make the variable have global scope). They also have `our` for aliasing global variables. It made me wonder whether we can use possessives to our advantage here.

**Comment by Divesh-Otwani** [comment]
I thought about this for bit and I have some thoughts:

- I think since it's going to be used so often, the name won't be too important so long as it's short and not deeply counter intuitive and confusing. I personally didn't find `Unrestricted` intuitive but after I understood the definition and how that worked with linear types, it didn't matter.
- I think names break down into two groups: conveying `Identity` in some way, or conveying that the value can be used `Freely` in some way. Intuitively, I prefer the latter. In any case, I think thinking about the names in this way is helpful in trying to figure out what we want.
- It might be easiest to just list out what we absolutely don't want and just find something good enough to meet that criterion?

**Comment by aspiwack** [comment]
While casually chatting with @mboes , a few days ago, this subject came up. Neither of us could shake the feeling that `Unrestricted` is the best name. It is both consistent with the literature and meaningful. It just has one issue: it is too long for something used that often.

So a shorten version of `Unrestricted` sound like the best approach.

We are leaning towards `Ur`. What you think?

**Comment by utdemir** [comment]
I am happy with `Ur`.

**Comment by Divesh-Otwani** [comment]
Yup; works for me.

**Comment by mboes** [comment]
Sounds like we have a winner. Close with a PR that changes the name.

**Comment by facundominguez** [comment]
Just an opinion, `Unr` is more suggestive to me than `Ur`. Maybe because it is a prefix of `Unrestricted`.

**Comment by b-mehta** [comment]
I agree, `Ur` to me suggests the German prefix rather than a contraction of `Unrestricted`: `UR` or `Unr` feel more appropriate in my opinion
