### ISSUE TITLE
Data.Array.Mutable.Linear.Array is unnecessarily strict

### ISSUE THREAD

**Issue by utdemir** [tweag/linear-base#142]
**Describe the bug**

As a result of #135, `Data.Array.Mutable.Linear.Array` is stricter than necessary; `read`'s force the elements to WHNF. This is counter-intutitive since most other Haskell collections are lazy on the values.

**To Reproduce**

```haskell
{-# LANGUAGE LinearTypes #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}

module Main where

import Data.Function ((&))
import qualified Prelude.Linear as L
import qualified Data.Array.Mutable.Linear as Array
import Prelude.Linear (Unrestricted(..))

processArr :: Array.Array () #-> Unrestricted ()
processArr arr =
  Array.write arr 0 (error "this should not be evaluated") L.& \arr ->
  Array.read arr 0 L.& \(arr, Unrestricted _) ->
    arr `L.lseq` Unrestricted ()

main :: IO ()
main =
   Array.fromList [()] processArr
     & \(Unrestricted a) -> print a
```

**Expected behavior**

We expect the above program to print `()`, however it currently fails.

We should also have a test case for this.

**Comment by Divesh-Otwani** [comment]
I think we should have unboxed and boxed variants. This could be useful for cache sometimes.

**Comment by facundominguez** [comment]
Is the issue fixed by
```
-readMutArr :: MutArr# a -> Int -> a
+readMutArr :: MutArr# a -> Int -> (# a #)
 readMutArr mutArr (I# ix) =
-   case doRead of (# _, a #) -> a
+   case doRead of (# _, a #) -> (# a #)
   where
     doRead = runRW# $ \stateRW -> readArray# mutArr ix stateRW
```
?

**Comment by facundominguez** [comment]
Using a continuation would also help
```
readMutArr :: MutArr# a -> Int -> (a -> b) -> b
readMutArr mutArr (I# ix) f =
  case doRead of (# _, a #) -> f a
  where
    doRead = runRW# $ \stateRW -> readArray# mutArr ix stateRW
```
I think `readMutArr arr i $ \a -> writeMutArr arr i 'b'` would play effects in the right order, although it is still possible to write the incorrect `let a = readMutArr arr i id in seq (writeMutArr arr i 'b') a`.

**Comment by aspiwack** [comment]
> Is the issue fixed by

I think so. Must be tried :slightly_smiling_face:

**Comment by utdemir** [comment]
> > Is the issue fixed by
> 
> I think so. Must be tried

It is :). I applied the change on @facundominguez's first comment, followed the types until it compiles, then added a test case on #143.
