### ISSUE TITLE
Array resizing functions are counter-intutive.

### ISSUE THREAD

**Issue by utdemir** [tweag/linear-base#148]
`Data.Array.Mutable.Linear` module comes with these functions:

```haskell
-- | Using first element as seed, resize to a constant array
resize :: HasCallStack => Int -> Array a #-> Array a
resize newSize (Array _ mutArr) =
  let !(# a #) = Unsafe.readMutArr mutArr 0
  in  Array newSize (Unsafe.newMutArr newSize a)

-- | Resize to a new constant array given a seed value
resizeSeed :: HasCallStack => Int -> a -> Array a #-> Array a
resizeSeed newSize seed (Array _ _) =
  Array newSize (Unsafe.newMutArr newSize seed)
```

I find them counter-intutive, since I don't expect a `resize` operation to lose most/all of the elements unless we are shrinking the array. I suggest we replace them with `growBy` and `shrinkTo` functions:

```haskell
-- | Grows the array by given number of elements, using a default value.
growBy :: HasCallStack => Int -> a -> Array a #-> Array a

-- | Shrinks the array to contain given number of elements.
shrinkTo :: HasCallStack => Int -> Array a #-> Array a
```

We can also provide a `resize` function can do both. Also; since these functions almost always copy the array, we can modify the signatures to return the original array too.

It seems like on the codebase `resizeSeed` function is used for allocating a new array using another array, without requiring a continuation. I think it is better done explicitly with a new alloc variant, something like:

```haskell
-- | Allocate a constant array given a size and an initial value,
-- using another array as a uniqueness proof.
allocBeside :: Int -> a -> Array b #-> (Array b, Array a)
allocBeside size val orig = (orig, Array (Unsafe.newMutArr size val))
```

I _think_ above is safe. Let me know if it isn't.

This issue is broken up from: https://github.com/tweag/linear-base/pull/146

**Comment by aspiwack** [comment]
> I _think_ above is safe. Let me know if it isn't.

It is (well, I'm pretty sure it is, anyway). See #130 .

> -- | Grows the array by given number of elements, using a default value.

Using a default value to what? Probably you should give the specification with maths, things like
> let `b = growBy n x a`, then `length b = length a + n`, and `b[i] = a[i]` for `i < length a`, and `b[i] = x` for `length a <= i < length a + n`.

I'm not sure that this is the semantics that you have in mind. But this is an unambiguous suggestion.

These are probably reasonable primitive (up to the details of the specification). But should probably be weighted against a single `resize` operation, where, when you know that you are shrinking, you can just pass `undefined` as the extra argument. Of course these are interdefinable sets of primitive, so it doesn't cost much having both (on of the small advantages of laziness).

**Comment by utdemir** [comment]
> Probably you should give the specification with maths.

Yes, I should. And that was the semantics I have in mind.

> But should probably be weighted against a single resize operation, where, when you know that you are shrinking, you can just pass undefined as the extra argument.

I would be fine with this. I'm now feeling strongly about having a single `resize` versus separate `grow` and `shrink`'s. Let's assume that my suggestion is to replace the `resize` function with following semantics:

> let b = resize n x a, then length b = n, and b[i] = a[i] for i < length a, and b[i] = x for length a <= i < n.

And replacing `resizeSeed` with the `allocBeside` function above.

**Comment by aspiwack** [comment]
This sounds reasonable to me.
