### ISSUE TITLE
Consume the continuation linearly when allocating linear collections

### ISSUE THREAD

**Issue by utdemir** [tweag/linear-base#150]
Currently, our mutable `Vector`, `Array` and `HashMap` constructors are of this form:

```haskell
alloc :: ... -> (Thing a #-> Unrestricted b) -> Unrestricted b
```

This is too ~~general~~ specific; since it doesn't mention that the continuation will only be used once, we can not use a linear value from the outer scope inside the continuation. Consider this example:

```haskell
data Thing = Thing
instance Consumable Thing where consume Thing = ()

withThing :: (Thing #-> Unrestricted b) -> Unrestricted b
withThing f = f Thing

doSomething :: Unrestricted Int
doSomething =
  withThing (\t1 ->
    withThing (\t2 ->
      t1 `lseq` t2 `lseq` Unrestricted 42
    )
  )
```

This does not compile, since `t1` is used inside the inner continuation, however the result of the inner `withThing` does not guarantee that it'll use the computation once.

To fix this, we should replace them with the form:

```haskell
alloc :: ... -> (Thing a #-> Unrestricted b) #-> Unrestricted b
```

**Comment by aspiwack** [comment]
> This is too general

Technically, this is, in the contrary, too specific :slightly_smiling_face: .
