### ISSUE TITLE
Expand the linear mutable vector interface

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#165]
Linear mutable vectors currently only provide simple reads and writes and a `cons` function. We should have some more primitives available so that at least other use cases can be implemented externally when necessary.

We can use [`Data.Vector` module from `vector` package](https://hackage.haskell.org/package/vector-0.12.1.2/docs/Data-Vector.html) as a reference. At minimum:

* Versions of `read` and `write` without bounds checking for performance reasons.
* Ability to remove elements (and the vector should shrink accordingly).
* `fromList` and `toList` functions.
* Ability to get a slice of a vector.
* `map` and `filter` functions.
* Instances like `Functor`, `Foldable`, `Consumable`, `Dupable` where appropriate.

**Comment by utdemir** [comment]
For the `Dupable` instance, I'll await the result of https://github.com/tweag/linear-base/issues/151.
