### ISSUE TITLE
Use `Unrestricted` more generously on linear collections interface

### ISSUE THREAD

**Issue by utdemir** [tweag/linear-base#175]
There are some cases where our linear collections return a value linearly when they could also return it within a `Unrestricted`. Here are some examples (See the `snd` of the return values):

```haskell
-- HashMap's
size :: HashMap k v #-> (HashMap k v, Int)
member :: Keyed k => HashMap k v #-> k -> (HashMap k v, Bool)

-- Mutable Vector's
length :: Vector a #-> (Vector a, Int)

-- Array's
length :: Array a #-> (Array a, Int)
```

As you can see, all the returned values are already `Movable`, so it is possible to leave those as is (hence the "bikeshedding" label). However, in my experience, frequently the first thing I do is to `move` them to `Unrestricted`. So, it causes some boilerplate. You can observe this by looking at the usages of above functions in our test cases for mutable collections; the vast majority of them are immediately followed by a `move`.

My suggestion is to wrap those values with an `Unrestricted`, so the users don't have to call `move`.

This issue is similar to https://github.com/tweag/linear-base/pull/155.

**Comment by Divesh-Otwani** [comment]
I agree :smile:  The main reason I didn't was because `Unrestricted` was too long.
