### ISSUE TITLE
HashMap test failure caused by innocent code change

### ISSUE THREAD

**Issue by utdemir** [tweag/linear-base#184]
I found an issue at the mutable HashMap implementation on current master (`191bade`) alongside with a way to reliably reproduce it, however I couldn't pinpoint the exact problem. This issue is just to track my findings.

Here's the reproducer:

```haskell
--- a/src/Data/HashMap/Linear.hs
+++ b/src/Data/HashMap/Linear.hs
@@ -118,13 +118,13 @@ empty :: forall k v b.
   Keyed k => Size -> (HashMap k v #-> Ur b) #-> Ur b
 empty sz@(Size s) scope =
   alloc
-    s
+    16
     ( -1
     , ( error "reading error hashmap key"
       , error "reading error hashmap val"
       )
     )
-    (\arr -> scope (HashMap sz (Count 0) arr))
+    (\arr -> scope (HashMap (Size 16) (Count 0) arr))
 
 -- | If the key is present, this update the value.
 -- If not, if there's enough space, insert a new pair.
```

With the above patch, various HashMap tests fail with mismatching expected and actual values. Here is where it gets interesting:

* That value should not matter, since it's just the initial capacity of the `HashMap`. It should grow automatically.
* As far as I can see, we're already passing `16` as the size parameter from the tests. So, something is breaking referential transparency.

Since I do not want to believe the second point above, it's likely that I'm missing something crucial. @Divesh-Otwani do you have an idea?

**Comment by aspiwack** [comment]
Let's address #177 first, I think. It'll be easier on sounder foundations.

**Comment by Divesh-Otwani** [comment]
I'll take a look in a bit.

**Comment by utdemir** [comment]
@aspiwack I agree that that #177 might fix this. However, although it is likely, I am still not sure if this issue is indeed caused by the `Array` implementation, and I would like to know of the reason of this one. It might be caused by an issue we're not aware of.

I spent the entire day looking at this, without making much progress.

What I could find is somehow the fact that we're evaluating the `sz` parameter fixes the issue. Which is odd, since that `sz` parameter is pretty much a constant, and not used anywhere else.

I was able to reduce the test case to:

```haskell
test1 :: Property
test1 = withTests 57 . property $ do
  k <- forAll key
  let ret = unur Linear.$ HashMap.empty (HashMap.Size 16) Linear.$ \hm ->
        HashMap.insert hm k ""
          Linear.& \hm -> hm `lseq` Ur True
  assert ret
```

and the relevant code to:

```haskell
-- | Run a computation given an empty hashmap
empty :: forall k v b.
  Keyed k => Size -> (HashMap k v #-> Ur b) #-> Ur b
empty sz' scope =
  alloc
    s
    ( -1
    , ( error "reading error hashmap key"
      , error "reading error hashmap val"
      )
    )
    (\arr -> scope (HashMap sz (Count 0) arr))
 where
  sz@(Size s) = sz' `seq` Size 16 -- This is the important line
```

Using the above functions, the test pass when `seq` is there, and goes into an infinite loop when it is removed (replaced by `sz@(Size s) = Size 16`). This is strange, since that `sz'` is not used anywhere else and it shouldn't have any effect on the actual values we're storing inside the `HashMap`. I think there is an undefined behaviour somewhere where seemingly irrelevant changes corrupts the `HashMap`'s underlying `Array`.

I think it is likely to end up being relevant to #177. But it would be good to figure out exactly how.

**Comment by aspiwack** [comment]
Let me put it this way: if `seq` changes the meaning of something (well, `seq` is allowed to make more things diverge, but that's not that we are observing), then there is something which claims to be pure, yet isn't. It's a bug in an unsafe bit. So, if there is no unsafe bits in hashmap (as I believe is the case), the hashmap module is not, itself, the cause.

Since we are planning to move and reduce the unsafe bits, there is not really a point in trying to understand this particular problem, unless it shows up again in our strengthened implementation.
