### ISSUE TITLE
Order of the returned tuple when threading linear values varies across different modules

### ISSUE THREAD

**Issue by utdemir** [tweag/linear-base#191]
Pretty pointless bikeshedding issue ahead, I apologize.

Working with linear values usually require threading the linear value from function to function, and when functions also return another result, they return a tuple of the linear value and a (usually unrestricted) result.

However, the order of the linear value and the result at the returned tuple varies from module to module in `linear-base`. Here're some examples:

```haskell
-- System.IO.Resource and polarized array modules return the threaded value on `snd`
hGetChar :: Handle #-> RIO (Ur Char, Handle)
findLength :: Pull.Array a #-> (Int, Array a)

-- Linear mutable collections (arrays, vectors, hashmaps and sets) return the thread value on `fst`
size :: Vector a #-> (Vector a, Ur Int)
read :: HasCallStack => Vector a #-> Int -> (Vector a, Ur a)
```

As a user, although it is not a huge deal because of the types, it would still be annoying to having to remember where to expect the return value; I think there is value in consistency. So, we should make a decision here.

In my opinion, there is no clear advantage of either direction. So, let's pick one and use it across the codebase, if there is no objection.

**Comment by aspiwack** [comment]
That's my fault. Let's use the same order as `State` for consistency.

**Comment by utdemir** [comment]
:+1:.  Looking at `runStateT :: s -> m (a, s)`, the threaded value will go to `snd` and the interface will look like polarized arrays. I will send a PR.
