### ISSUE TITLE
Change the name of vector of known length to…

### ISSUE THREAD

**Issue by aspiwack** [tweag/linear-base#207]
As mentioned somewhere (I forget where) by @utdemir , there is an unfortunate clash of terminology in linear-base.

We did not make this: the word _vector_ is used, in the Haskell ecosystem, both to mean a slightly more flexible array (basically used as a synonymous of array here), and as a one-dimensional matrix with a size in their type.

By mimicry to the [linear](https://hackage.haskell.org/package/linear) (which, ironically, is also completely unrelated to linear types: it's about linear algebra), I used `V` as the name of the type (I just noticed that linear also defined V0, V1, V2, V3, and V4 separately, I don't know why). Though I used `Vector` as the library name, linear uses `V` as well. And `Vector` clashes with the other `Vector` library.

So, we have two choices:
- rename the library to `V`
- rename the library and the type to something else (maybe `Tuple`, but [then again…](https://hackage.haskell.org/package/base-4.14.0.0/docs/Data-Tuple.html))

**Comment by utdemir** [comment]
I agree that it is unfortunate. I think renaming the module name to  `V` makes sense.

The only unfortunate thing is the module name would look strange (`Data.V.Linear`?). I thought about something like `Data.Vector.{KnownLength,LengthIndexed}` (and keeping the type name `V`), but it is wordy. 

So, in short, I think we should rename it to:

* Module name: `Data.V.Linear`
* Type name: `V`

Unless there is another widely used name for these kind of things.

**Comment by Divesh-Otwani** [comment]
I second @utdemir.

**Comment by aspiwack** [comment]
Let's then.
