### ISSUE TITLE
Rename one-letter qualified imports in linear-base

### ISSUE THREAD

**Issue by utdemir** [tweag/linear-base#229]
Some of the modules are imported as single-letter acronyms, which is not readable. eg at: `examples/Spec.hs`:

```haskell
import qualified Prelude as P
```

We should use more descriptive names here.

**Comment by Divesh-Otwani** [comment]
Shouldn't this be closed?

**Comment by utdemir** [comment]
I think those PR's weren't comprenhesive, since they did not touch `Optics` and `Streaming` modules, I was able to find a few occurrences:

```

src/Streaming/Prelude/Linear.hs
18:> import qualified Streaming.Prelude as S
28:> import qualified Pipes as P
29:> import qualified Pipes.Prelude as P

src/Control/Optics/Linear/Internal.hs
51:import qualified Prelude as P
```
