### ISSUE TITLE
Integrate `doctests` to type-check inline examples

### ISSUE THREAD

**Issue by utdemir** [tweag/linear-base#235]
Since `linear-base` codebase is changing a lot these days, inline code snippets in our Haddock's can get out of sync, as seen on #234.

We should integrate `doctest`, so our CI can catch those errors. This will change the overall style of the examples a bit, since they currently demonstrate entire modules; but with `doctests` they will look more like REPL sessions. eg:

```haskell
>>> :set -XLinearTypes
>>> :set -XQualifiedDo
>>> import qualified System.IO.Resource as Linear
>>> import qualified Control.Monad.Linear as Control
>>> import qualified Data.Text as Text
>>> import Prelude.Linear
>>> import qualified Prelude
>>> :{
 linearWriteToFile :: IO ()
 linearWriteToFile = Linear.run Prelude.$ Control.do
   handle1 <- Linear.openFile "/home/user/test.txt" WriteMode
   handle2 <- Linear.hPutStrLn handle1 (Text.pack "hello there")
   () <- Linear.hClose handle2
   Control.return (Ur ())
:}
```

To me, this is unfortunate. But I couldn't think of a better way to keep those examples correct; and the benefits outweigh the cost, I think.

**Comment by Divesh-Otwani** [comment]
I tried this a while back and getting the build to work was tricky for some reason. But in general, yes I second.
