### ISSUE TITLE
Dupable and Consumable

### ISSUE THREAD

**Issue by andrewthad** [tweag/linear-base#24]
`Dupable` is dual to `Semigroup` (I have it named `Cosemigroup` in an experiment I'm working on), and `Consumable` is dual to `Monoid`. But the superclass relationship is reversed in this library. Is there a fundamental reason for this? I have a hard time seeing which way it should actually be.

**Comment by aspiwack** [comment]
I don't think I have one without the other very often, to be honest. So it's hard to make a truly informed decision. My intuition, though, is that there are often situations where we only need to consume things, whereas situation where we need to duplicate things tend to also need to consume things somewhere.

It's mostly only an intuition but whereas I've used `Consumable` (aka Copointed) constraints in a number of places, there are no place where I would have felt better having a `Cosemigroup` constraint.

As a more technical aside, I'd like to generalise `a ->. (a, a)` into `KnownNat n => a ->. V n a` (where `V n` is a vector of size `n :: Nat`). This would prevent unnecessary allocations here and there. But it would be rather annoying to have to exclude `0` from such a function artificially.

**Comment by andrewthad** [comment]
On the theory side, one could argue that `Consumable` has no laws unless there is also a `Dupable` instance, which hints that `Dupable` should be the superclass. But, maybe the implied law is something like "is this type inhabited?", since instances of `Consumable` always have exactly one possible implementation.

On the industry side, I have come across a type I use that has a `Dupable` instance but not a `Consumable` instance: state tokens. Consider the following type:

```
data Token = Token (State# RealWorld)
instance Semigroup Token where ...
instance Dupable Token where ... -- aka Cosemigroup
```

Clearly, we need new primops to actually write these instances (although I've been working around this with some judicious `NOINLINE` and `unsafeCoerce`). Something like:

```
dupState# :: State# s ->. (# State# s, State# s #)
jamState# :: State# s ->. State# s ->. State# s
```

Equipped with these instances, we can fork (logically, not in the sense of concurrency) and join. However, in this API, I don't particularly want users to be able to `consume` a state token, since that would cause GHC to discard the effectful computation I am trying to keep sequenced.

**Comment by aspiwack** [comment]
> On the theory side, one could argue that Consumable has no laws unless there is also a Dupable instance, which hints that Dupable should be the superclass

Frankly, I don't find this (common) argument convincing. Pointed or copointed objects show up a lot in category theory. That we don't have equational laws doesn't mean it's less useful as an abstraction.

> On the industry side, I have come across a type

Let's have the conversation in tweag/ghc#190 . And when I understand better, we can see about making the case for reversing this.

**Comment by aspiwack** [comment]
As we are getting close to release, we need to rule on this. I think that the current dependencies have served us well, so I'm ruling in favour of keeping it. If you very strongly disagree feel free to reopen.
