### ISSUE TITLE
Replace Hspec property tests with Hedgehog

### ISSUE THREAD

**Issue by utdemir** [tweag/linear-base#246]
We have some QuickCheck property tests written using Hspec at [examples/Spec.hs](https://github.com/tweag/linear-base/blob/ca1ae741a3e2fb9718edf13f32c45f82e397623c/examples/Spec.hs).

But, most of our tests are in using Hedgehog, under `test/` directory. Just for consistency, it would be good to move the `Spec.hs` file under `test/` directory and migrate the cases there to use Hedgehog. We can also possibly save a few test dependencies in the process.

**Comment by aspiwack** [comment]
The job of `example/Spec.hs` is to test that the examples work as advertised. Maybe some of the tests should be moved to `test/` but most shouldn't.

I'm ok if they are moved to hedgehog, though.

**Comment by utdemir** [comment]
Thanks, I didn't know that there are some of them testing the examples. Looking at it more carefully, I think "Off-heap lists" and "Off-heap heaps" sections are about examples (line 35-74); but the "linear arrays" section (line 75-) seems like about destination and polarized arrays which don't depend on any examples.

So, yes, if a test case is about an example, it should stay there; but others can be moved.

Also, I think `TopSort` example defines some tests, but they are as far as I can see they aren't invoked by any entrypoint, so we should probably add them to `Spec.hs`.

**Comment by Divesh-Otwani** [comment]
I'd like to move the tests to `test/` and use `tasty` for just literal, simple examples.

**Comment by aspiwack** [comment]
As long as `test` doesn't depend on `examples` and that no bona fide example is removed from `examples`, I'm fine with anything. `stack test` will, I believe, run both test-suite by default.
