### ISSUE TITLE
Expand `Data.V.Linear` API

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#250]
**Is your feature request related to a problem? Please describe.**

The length-indexed vectors in `Data.V.Linear` are useful with linear uses of vectors. We can do things like only `zip` vectors of the same length and thereby consume each linearly. They are also useful for defining `dup` instances. The rub is that they are kind of complicated and hard to use right now. We want it to be much simpler.

**Describe the solution you'd like**

An API like that of `Data.List.Linear` with length-indexed vectors. We can't use a plugin for fancy type level computations so we'll have to make do with workarounds that should be reasonably simple. The goal is linear-variants what we can do with normal lists without letting things get too complicated.

**Comment by aspiwack** [comment]
I don't understand this issue's title.

Also, `Data.V.Linear` is not really about lists. In many respect, they are more like tuples.

We don't want anything like `filter` (we don't know the length of a filter lists). We probably want a `split` on pull Vs, and an `append` on push Vs (see #208 ). But these are probably the only size-manipulating functions that we will add at first.

Consumption functions (probably traversable-by-data and its consequences as in #190 ) are fair game, though.

However, strive for issues which have an end. I this one probably doesn't, and should be split in a number of sub-issues.

**Comment by Divesh-Otwani** [comment]
Length indexed vectors are useful in their own right and have solutions to things like `filter`. I imagined we wanted something like [`vec`](https://hackage.haskell.org/package/vec) but with linear types. 

The end would be when we have a minimal collection of the API from `vec`.

Looking back, I don't think that's very useful and would prefer to just use push-pull versions. Close the issue?

**Comment by aspiwack** [comment]
> Length indexed vectors are useful in their own right and have solutions to things like `filter`. I imagined we wanted something like [`vec`](https://hackage.haskell.org/package/vec) but with linear types.

They are, and they have (though it's not very interesting: a filter returns something of an unknown length, that you must then reason abstractly about). But I strive for something simple, where the client always use either concrete values for type-level lengths, or one arbitrary value but without arithmetic (like in the `Applicative` instances).

At least for the time being.

> Looking back, I don't think that's very useful and would prefer to just use push-pull versions. Close the issue?

It's probably too open-ended to be fully useful. Let's probably try and expand the API lazily: when a particular use-case shows up that needs extra support, then see what we can do.
