### ISSUE TITLE
Destination array newtype wrapper

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#289]
In `Data.Array.Destination`, we should replace

```haskell
newtype DArray a = DArray (MVector RealWorld a)
```

with 

```haskell
data DArray a where
  DArray :: !MVector RealWorld a -> DArray a 
```

**Comment by aspiwack** [comment]
And remove most (all?) calls to `Unsafe.toLinear`.

**Comment by aspiwack** [comment]
The original thinking is this comment https://github.com/tweag/linear-base/pull/287#discussion_r552437657

But to widen the horizon a bit, we should probably never write a `newtype` when creating a linear abstraction over an unrestricted API. At least not if it forces us to use `Unsafe.toLinear`. Using `Unsafe.toLinear` when a newtype is involved is pretty dangerous. And likely to be incorrect.

We usually really need a data with an unrestricted field to mediate between the linear and unrestricted world.

I originally wrote this newtype. And I have not the slightest memory of why. I don't know if I thought about it or if I just wrote it out of habit from non-linear Haskell. But either way, I don't think, today, that this newtype is restricted.
