### ISSUE TITLE
Export a Data.Array.Mutable.Linear.Internal that exposes the Array constructor

### ISSUE THREAD

**Issue by ekmett** [tweag/linear-base#305]
**Is your feature request related to a problem? Please describe.**
I started writing a `linear-base` interop library for `primitive`. I got stuck very early on in the process because I can't access the `Array` constructor. So none of my arrays can be compatible with yours. I'm currently stuck cutting and pasting all your code.

**Describe the solution you'd like**
Export a `.Internal` module that exposes the implementation details for Array. Preferrably do this for each of the concealed types, because I'll be bitten by them all eventually.

**Describe alternatives you've considered**
Forking the universe. Based on previous efforts, I anticipate this to take at least 7 days.

**Additional context**

**Comment by aspiwack** [comment]
Fair enough. Let's do this. I'm not sure any of us has time in the next two weeks though. But I'll make a note to come back to it after that.

**Comment by ekmett** [comment]
FWIW- re: alternatives I've considered, my usual hack of doing something like

```haskell
do                                                                                         
  TyConI (DataD _ctx _name _tyvarbndrs _mkind [NormalC con _] _derivs) <- reify ''Array    
  let a = mkName "a"    
  Prelude.sequence                                                        
    [ patSynSigD (mkName "Array") [t| forall a. Array# a -> Array a |]             
    , patSynD (mkName "Array") (prefixPatSyn [a]) implBidir (conP con [varP a])    
    ]
```

doesn't work here due to the lack of support for linear types in pattern synonyms.
