### ISSUE TITLE
relax the type of alloc

### ISSUE THREAD

**Issue by ekmett** [tweag/linear-base#307]
**Is your feature request related to a problem? Please describe.**
When building mutable structures with mutable arrays as components I find myself wanting to just alloc several of them indeoendently. But right now I'm forced to produce a final result in `Ur`.

**Describe the solution you'd like**
I'm not an expert on linear types in haskell yet, but at least to my naive reading,

```haskell
alloc :: HasCallStack => Int -> a -> (Array a %1 -> Ur b) %1 -> Ur b
```

should probably be

```haskell
alloc :: HasCallStack => Int -> a -> (Array a %1 -> b) %1 -> b
```

Maybe we document that 'most of the time' users should expect b to be something of type `Ur whatever`, but the implementation doesn't seem to have anything that needs `Ur` there, freeing up the use of linear results.

**Describe alternatives you've considered**
I can use allocBeside but not I have to care whether or not I'm building the base case or have already built one, doubling up my implementation, and making it impossible to 'unfold' into one, where i might have or might not have needed to build such an array in a different branch of the unfold and not locally know.

**Additional context**

**Comment by Divesh-Otwani** [comment]
This would break type safety. See the user guide [here](https://github.com/tweag/linear-base/blob/master/docs/USER_GUIDE.md#f--x---sometype-1--ur-b-1--ur-b-functions). 

```haskell
import qualified Prelude.Linear as Linear

x :: Array a
x = alloc 10 0 Linear.id

breakSafety :: Array a -> (Array a, Array a)
breakSafety arr = dualRead 1 (write 1 100 arr, write 1 99 arr)
 
dualRead :: Int -> (Array a, Array a) -> (a,a)
dualRead i (a1, a2) = (read a1 i, read a2 i)
```

I'm not sure what would be a good solution to the multiple allocation you're looking for would be.

**Comment by sjoerdvisscher** [comment]
Maybe this is too much of a hack, but you could use `allocBeside` with a dummy 0-size array, which can be passed around with the linear state monad.

**Comment by aspiwack** [comment]
For the sake completeness, we have a discussion on this sort of things here: https://github.com/tweag/linear-base/issues/130 .
