### ISSUE TITLE
Consumable/Dupable (V n a)

### ISSUE THREAD

**Issue by ekmett** [tweag/linear-base#310]
**Is your feature request related to a problem? Please describe.**
I was implementing an API on top of V n a, and needed to drop the whole V.

**Describe the solution you'd like**

```haskell
instance Consumable a => Consumable (V n a) where
  ...
instance Dupable a => Dupable (V n a) where
  ...
```

These are just tricky enough that it seems worth building them in house, and the unsafe implementation is probably faster than what can be done through the public API.

**Describe alternatives you've considered**

orphan instances, mostly.

**Comment by aspiwack** [comment]
Indeed, this is definitely an oversight on our part. Thanks for raising it up.
