### ISSUE TITLE
Data.Functor.Linear.Internal.Foldable

### ISSUE THREAD

**Issue by ekmett** [tweag/linear-base#313]
Creating this issue mostly to track the questions about the design of a linear Data.Foldable.

**Is your feature request related to a problem? Please describe.**
Right now you have to jump clear to Traversable, meaning a linear `Set` has to use one-off functions for most of its combinators, rendering the code feeling much less like normal Haskell.

**Describe the solution you'd like**
Linear Data.Foldable

**Describe alternatives you've considered**
This may not be entirely possible to have this as a superclass of linear Traversable. Why? Consider a `Map k v`. `Foldable.toList` is going to collect the `v`'s into the output list but not the `k`'s, so Foldable will require some ability to `consume` the rest of the structure, which isn't an issue innately required by `Traversable`, as the Traversable code passes through the structure unmolested.

This lack of relationship between these two concepts currently shows up in the linear lens hierarchy as the lack of Folds, and the fact that Traversals don't intrinsically upgrade to Folds like they do in normal haskell.

This points to there being some point in the optic space where you have a structure with consumable extra parts that is both a `Traversal` and a `Fold`, e.g. morally where the bokeh of the traversal (or a lens), the stuff that is out of focus, or constant complement, is Consumable. The same issue arises with `Lens` and `Getter`.

**Comment by sjoerdvisscher** [comment]
This is basically issue #190, once you have a `Traversable` with `Data.Applicative`s, you can derive `Foldable` with `Const` as usual. For `Map k v` you can then do `instance Consumable k => Foldable (Map k)` and `instance Movable k => Traversable (Map k)`.

**Comment by ekmett** [comment]
Consolidating into #190.
