### ISSUE TITLE
Submit linear-base to Stackage

### ISSUE THREAD

**Issue by utdemir** [tweag/linear-base#333]
[The latest stackage nightly comes with GHC 9](https://www.stackage.org/blog/2021/05/2021-05-29-upcomming-ghc-9-on-nightlies), which enables us to add `linear-base` to Stackage. Both our library, test and benchmark dependencies compile on that nightly (https://github.com/tweag/linear-base/pull/332).

Before we add it to Stackage, here're the questions that come to my mind:

* I think @aspiwack would be the maintainer (same as for Hackage), but it would be good to confirm before I send a PR using his name :).
* Whether we should submit the current version, or wait until we release the next one. Since it is not a LTS snapshot yet, I don't think there's much reason waiting until our next release.

**Comment by aspiwack** [comment]
We can submit the current version. I don't much care who the maintainer is, you can be :slightly_smiling_face: . The Stackage maintainer is mostly a point of contact if the package breaks, I believe. Either of us will reach the team, so both work.

**Comment by utdemir** [comment]
I submitted https://github.com/commercialhaskell/stackage/pull/6085, and I added you as a maintainer (Both to be consistent with Hackage, and I do not know how long I will be working on `linear-base`).

I will close this issue once `linear-base` is in a nightly.
