### ISSUE TITLE
Linear Instances?

### ISSUE THREAD

**Issue by oliverbunting** [tweag/linear-base#339]
Are any of the following possible? Trialling them suggests not, and with random poking around in base I've not been able to find a single instance of  `(%One->)` `(%Many->)`, `(%1->)`, or `(%p->)` for a typeclass in `linear-base`

```haskell
instance (%One ->) where
instance (%Many ->) where
```

Is there some documentation on this I've overlooked?

**Comment by monoidal** [comment]
`(%One->)` is written `FUN One`, e.g. see https://github.com/tweag/linear-base/blob/bbd1ac76fcf8ba4a19892e35609b0ad1936a5355/src/Data/Profunctor/Linear.hs#L143. `FUN` is currently the only available prefix syntax for `a % m -> b`; see https://gitlab.haskell.org/ghc/ghc/-/issues/19639.
