### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by treeowl** [tweag/linear-base#345]
Add linear-typed wrappers for `GHC.Generics` `to`, `from`, `to1`, and `from1`. This should, I imagine, support default implementations of `Consumable` and such.

**Comment by aspiwack** [comment]
For completeness, let me link to the PR where we've attempted doing so: #316.

**Comment by treeowl** [comment]
@aspiwack, I just finished hacking up a Template Haskell implementation of a modified `Generic1`, implemented as a modification of `generic-deriving`: https://github.com/dreixel/generic-deriving/pull/77. Whether that pull request is accepted or not, the relevant portions could be dragged into `linear-base`. This modification avoids any `fmap`s whatsoever in `from1` and `to1`, so there's no need to worry about whether they're linear or not. Also, since they don't exist they don't have a performance penalty.

**Comment by aspiwack** [comment]
@treeowl this looks extremely clever. However, to my dismay, my brain is quite toast today. Could you explain to a poor soul how associating composition to the left avoids a use of `fmap`?

**Comment by treeowl** [comment]
@aspiwack, the way GHC does it takes something like `Either e (Maybe a)` and turns it into `Either e :.: Rec1 Maybe`. That means `Right (Just a)` has to become `Comp1 (Right (Rec1 (Just a)))` (or something like that; I'm sleepy). Pushing that `Rec1` newtype constructor down (or pulling it back out) requires mapping through all the composed types. On the other hand, the way I did it turns that type into something like `Rec1 (Either e) :.: Maybe`. That turns `Right (Just a)` into something like `Comp1 (Rec1 (Either e (Just a)))`. All the newtype constructors are on the outside, where we want them!

The way it's currently done was based on an intuitive guess: the term-level `(.)` naturally associates to the right, and the designer of `Generic1` figured it should work that way for representation composition. Since what he got basically *worked* (though inefficiently), he figured he was done. Oh well.

**Comment by treeowl** [comment]
Oh yeah, and in bigger compositions the `Comp1`s march through too, though I don't think that makes it any worse. Point is, if you want a new `Generic1`, it should probably be more like this one. Note that there are also fancier things like `kind-generics` that might be able to do the job; I don't understand that yet.

**Comment by treeowl** [comment]
This is now [its own package](https://hackage.haskell.org/package/linear-generics), with Template Haskell machinery based on `generic-deriving`.
