### ISSUE TITLE
Is fromSystemIO really safe?

### ISSUE THREAD

**Issue by treeowl** [tweag/linear-base#347]
I don't know much about linearity, but when I saw that, one concern popped out immediately. Lazy `IO` is based on `unsafeInterleaveIO`, which is hardly linear. Is it still safe in context for some reason?

**Comment by aspiwack** [comment]
I'm not entirely sure what your objection is. But is the fact that `fromSystemIO = unur <.> fromSystemIOU` an answer to your question?

**Comment by treeowl** [comment]
I haven't the slightest idea what that means/how it relates. Sorry. Have you looked at the source of `unsafeInterleaveIO`?

**Comment by treeowl** [comment]
Oh, I think I was thinking stupid.
