### ISSUE TITLE
Prelude asTypeOf isn't very useful

### ISSUE THREAD

**Issue by treeowl** [tweag/linear-base#354]
The linear prelude exports

```haskell
asTypeOf :: a %q-> a -> a
asTypeOf = const
```

That seems practically useless in a linear context. The traditional alternative is found in `Data.Proxy`, and can be given the following type:

```haskell
asProxyTypeOf :: a %q-> proxy a -> a
asProxyTypeOf a _ = a
```

Of course, if one is using `TypeApplications`, `id` is also an option. But I'd consider just removing `asTypeOf` here.

**Comment by tbagrel1** [comment]
Note for #393 #377 : Remove it from "Polymorphise ..." and add it as breaking change
