### ISSUE TITLE
`Foldable` (`Traversable` for `Data.Applicative`)

### ISSUE THREAD

**Issue by tbagrel1** [tweag/linear-base#370]
Some structures can be traversed by a `Data.Applicative` (and not just a `Control.Applicative`). It would be interesting to have such a class.

For example, it would give an easy implementation of `Dupable` or `Movable`:

```haskell
instance Dupable a =>  Dupable (MyDataTraversableByDataApplicative a) where
  dupR = traverseD dupR
```

**Comment by aspiwack** [comment]
There is an issue where we discuss this already: #190 .

**Comment by tbagrel1** [comment]
Closing for duplicate with https://github.com/tweag/linear-base/issues/190.
