### ISSUE TITLE
Add `evalState` (to `Control.Functor.Linear`)

### ISSUE THREAD

**Issue by andreasabel** [tweag/linear-base#404]
`evalState` is a common use-case of the state monad.
```haskell
import Control.Functor.Linear
import Data.Tuple.Linear

evalState :: Consumable s => State s a %1 -> s %1 -> a
evalState m s = fst (runState m s)
```
Probably there should also be `evalStateT`.

**Comment by aspiwack** [comment]
I'm not sure that `evalState` is quite as useful as in the case of the unrestricted-state monad. That being said, I'll welcome a PR, but see my thoughts in https://github.com/tweag/linear-base/issues/405#issuecomment-1094625847.

**Comment by andreasabel** [comment]
Maybe I can do without it, but I didn't see how because of the `Ur` in the type of `HashMap.empty`.  I'd be happy for advice, see my code at: https://gist.github.com/andreasabel/f5c877491d32b653efba44cb283ba490#file-interpretermain-hs

**Comment by andreasabel** [comment]
> So if this is an admissible generalization, ...

I ain't...

**Comment by andreasabel** [comment]
@aspiwack : I am back to `evalState`, see
- #411 

If you have other ideas how to write https://gist.github.com/andreasabel/f5c877491d32b653efba44cb283ba490#file-interpretermain-hs , please let me know.
