### ISSUE TITLE
Movable for amortized structures

### ISSUE THREAD

**Issue by treeowl** [tweag/linear-base#445]
In some cases, a pure amortized data structure may only be efficient when used in a single threaded fashion. This suggests a linear interface

```haskell
-- Pairing heaps
data PQ a = ...

-- Return the old heap and the new one
-- This is fine because these operations are
-- "cheap"
insert :: Ord a => a -> PQ a %1-> (PQ a, PQ a)
merge :: Ord a => PQ a %1-> PQ a %1-> (PQ a, PQ a)

-- Return only the new heap. This operation is "expensive", so working on old versions afterwards would pay credit that's already been spent.

extractMin :: Ord a => PQ a %1-> Maybe (Ur a, PQ a)

-- Sometimes you know your specific sequence of operations will be fine because you'll perform enough additional cheap operations before performing an expensive one. Return the old heap and the new. If the heap starts off empty, then it's consumed.

extractMinRiskingSlowness :: Ord a => PQ a %1-> Maybe (Ur a, PQ a, PQ a)
extractMinRiskingSlowness = unsafeToLinear $ \pq ->
  case extractMin pq of
    Nothing -> Nothing
    Just (a, pq') -> Just (a, pq, pq')
```

Would it be appropriate for something like `PQ a` to be an instance of `Moveable`? If so, should `move` be a no-op (`move = Unsafe.coerce Ur`), or should it fully reassociate the queue into a "safe" configuration that has no credit? What's the idiom? Do we want to provide a module giving an example of a structure like this?

**Comment by treeowl** [comment]
Sorry, I garbled this. Will reopen.

**Comment by aspiwack** [comment]
I don't think that it's ever ok to make `move` a no-op.

Ok, that's a little strong. It's not ok to make `move` a no-op if the data structure can contain a thunk (so it's ok for `Int#`…).

Why is that? Maybe you have a linear `x` variable that is captured by this thunk. You can't know: closures are existentially quantified over everything they capture. To make sure that you've consumed `x`, you have to force the thunk. As soon as your structure is moved, you can't guarantee that you will.

Now, if you keep the data structure fully strict, with no thunks inside, then you're probably good. I don't have good mathematical tools, to think through this yet, though. Always proceed with care :slightly_smiling_face:

**Comment by treeowl** [comment]
The structure I'm talking about holds only unrestricted values, so your concern about strictness isn't relevant.

Thinking about it again, I believe `move` actually is possible for a pairing heap. It reassociates the heap into what amounts to a sorted list, which is the "ground state", so to speak.

**Comment by aspiwack** [comment]
> The structure I'm talking about holds only unrestricted values, so your concern about strictness isn't relevant.

It is though, because of the linked structure of the pairing heap, independently of the data held in the nodes.

> Thinking about it again, I believe move actually is possible for a pairing heap. It reassociates the heap into what amounts to a sorted list, which is the "ground state", so to speak.

I'm not sure what implementation of `move` you have in mind, actually.

**Comment by aspiwack** [comment]
This implementation of move is unproblematic. You can implement it client-side too. You could also simply implement `move` as a simple recursion through the `PQ` concrete definition (the one you get from the `Generic` implementation). (though now, I'm not sure what you were speaking of `Unsafe.coerce` in the original post).

Is your question philosophical? Like “is it a good idea to have `move` even though the performance characteristics are not good, as it feels so easy to use“? If so, it's a similar point that I brought up at #206 .

**Comment by aspiwack** [comment]
Aha! Very interesting.

So the idea is, in an amortized structure, you do a bunch of cheap operations, but eventually you have to do an expensive operation. You certainly don't want to do the expensive operation many times, so you want an implementation of `move` forces the expensive operation to happen, so that the shared data structure is in a state where the next operations are going to be cheap for a while.

This is an alternative to Okasaki's style laziness, where you the expensive operation is shared/memoised. Probably easier to implement too. It also reminds me of this limitation of laziness I [tweeted about last year](https://twitter.com/aspiwack/status/1537813421923901440).

**Comment by treeowl** [comment]
Yes, that's the idea. Okasaki-style structures (e.g., lazy-spined binomial queues as in the `pqueue` package I co-maintain) are great when you use persistence heavily. But in many non-persistent or lightly persistent settings those can be overkill. The sorting functions in `Data.Sequemce` use pairing heaps, for example, because @lowasser (and layer @oisdk) found they performed well in that application.

**Comment by aspiwack** [comment]
(well in their defence pairing heap are a very unfair data structure: they are dead simple, and perform well in many applications)

Is there anything left on this issue, that you'd want to achieve? Or should we close?

**Comment by treeowl** [comment]
I think there may be room for some documentation somewhere? I don't know if that belongs here, though, or in the GHC docs. In case you're curious, [this is the linear pairing heap implementation I hacked up](https://gist.github.com/treeowl/b092eade5ec4bf429eb8351e50909240).

**Comment by aspiwack** [comment]
I think (I'm pretty sure in fact) I wrote a comment here, and never finished. It got lost. Sorry. I'm seeing this again now.

What kind of documentation do you imagine? We can make it happen, I'm just not clear on what it could look like.
