### ISSUE TITLE
How ready is Linear Haskell for real world use cases?

### ISSUE THREAD

**Issue by YellowOnion** [tweag/linear-base#462]
It seems that Linear Haskell in GHC works, but progress on this library does seem a little slow (browsing some of the issues here)

If I was to start a project, like say [wrapping a c library](https://ffmpeg.org/doxygen/6.0/examples.html), should I consider using this?

Is there any way to help for a layman like me?

Are there any plans for integrating directly with rust's affine types too?

Is there a chat or mailing list I could join?

**Comment by aspiwack** [comment]
As a follow up, you were asking for chats: we now have a Discord: https://discord.gg/7yg5GxzvDJ .

**Comment by aspiwack** [comment]
Let me close as I believe the question has been answered.
