### ISSUE TITLE
Word does not have instances for the Data.Num.Linear typeclasses 

### ISSUE THREAD

**Issue by Qqwy** [tweag/linear-base#466]
**Describe the bug**
It is currently impossible to use `Word` in a module using `Prelude.Linear` as prelude, because [instances for Additive, Multiplicative, AddIdentity, MultIdentity, AdditiveGroup, Semiring, Ring, FromInteger and Num](https://github.com/tweag/linear-base/blob/074aeb8502c502f05ac0de142f3ccaf84a6b5ecc/src/Data/Num/Linear.hs#L211-L213) are missing for `Word`:

**To Reproduce**

```haskell
{-# LANGUAGE NoImplicitPrelude #-}
module Example where
import Prelude.Linear

add1 :: Word %1 -> Word
add1 = (+ 1)
```

**Expected behavior**
This should compile.

**Actual behavior**
Compile error: `No instance for (Additive Word) arising from the use of '+'`.

**Comment by aspiwack** [comment]
I would appreciate a PR, indeed. Thanks!
