### ISSUE TITLE
Clarify Ur documentation

### ISSUE THREAD

**Issue by tomjaguarpaw** [tweag/linear-base#476]
Perhaps change

> Its use is restricted while an argument in a non-linear function is unrestricted.

to

> Its use is restricted. By contrast, an argument in a non-linear function is unrestricted.

The former is easy to misinterpret as "Its use is restricted during the time period that an argument in a non-linear function is unrestricted", which is meaningless nonsense.

https://github.com/tweag/linear-base/blob/16795c74588d013bbb2d4cd7954fd129b8ad2c46/src/Data/Unrestricted/Linear.hs#L7

**Comment by aspiwack** [comment]
Sounds good to me. I'm back from my holiday. I can do it soon. But you can also scoop me and make a PR :slightly_smiling_face: .
