### ISSUE TITLE
Push Arrays

### ISSUE THREAD

**Issue by b-mehta** [tweag/linear-base#80]
The current type of Push Arrays does not allow some operations which ought to be possible for a Push Array: for instance folding into a monoid or unzipping. It seems that the `DArray ->. ()` ought to be generalised somehow; at the moment, the only way to consume a Push Array is to allocate.

**Comment by b-mehta** [comment]
I'm not arguing this should be re-opened, but to me there's still something somewhat unsatisfying going on here - like you mentioned, I think we're still missing the "use each index only once" property of pull arrays. Also, there's now two types for arrays: `ArrayWriter` and `Array`, and there doesn't seem to be any conversion from one to the other (unless I'm missing something?) - shouldn't we be able to allocate a Push Array?

**Comment by Divesh-Otwani** [comment]
1. I agree with the "use index only once" and maybe that should be an issue. 
2. There is only one type for an array. `ArrayWriter` is not an array and it is not exposed. It's something that will write to an array. The point of using the rank-2 thing is to avoid holding a computation that can't represent "write to a number of cells exactly once". An `ArrayWriter` is not a push-array, and you could see this by trying to implement the push-array API with it. 
3. We can allocate a push array, by `alloc`. Or do you mean allocate before we start writing to it? It seems like that would be a use-case for destination arrays.

**Comment by b-mehta** [comment]
Ah I see, thanks for explaining! I was misunderstanding the use and meaning of `ArrayWriter`, it makes sense now - I thought it was a different version of a push array which can be allocated, but it's just an internal type which allows allocation of a genuine `Push.Array`.
