### ISSUE TITLE
Multiplicity Polymorhphic (Relative) Monads for Resources

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#83]
#The type of bind in the RIO and Linear monads ought to be polymorphic.

This is an instance of #27.

For instance, we should have the following:

```haskell
(>>=) :: RIO p a #-> (a ->.(p) RIO p' b) #-> RIO p' b
```

We currently have (in System.IO.Linear and System.IO.Resource) the following:
```haskell
(>>=) :: RIO a #-> (a #-> RIO b) #-> RIO b
(>>) :: RIO () #-> (RIO b) #-> RIO b
```

**Comment by aspiwack** [comment]
This is an instance of #27 . In the current implementation, this is not yet supported.

**Comment by Divesh-Otwani** [comment]
Ok, I'll migrate it if need be and close it in a bit.

**Comment by Divesh-Otwani** [comment]
Yes, let's close.
