### ISSUE TITLE
Mutable Vectors replicate Mutable Arrays

### ISSUE THREAD

**Issue by Divesh-Otwani** [tweag/linear-base#90]
Right now, mutable vectors and mutable arrays both use Unsafe.MutableArray. Most of what Vector does repeats code from mutable arrays.

This should be fixed, probably by implementing mutable vectors in terms of mutable arrays, or just by having one array type with the functionality of both.

**Comment by utdemir** [comment]
I'm closing this in favour of #144, just because that one is newer and has an (obsolete) PR linked.
